### PR TITLE
fix: Updated rating for シュガーソングとビターステップ

### PR DESCRIPTION
**Pull request by rithik-b**
Should be a 10 instead of 10+ since the difficulty is 10.4

### CODE REVIEW

**Comment by zkrising** [comment]
Odd. I wonder why this was wrong in the first place?

What are the requirements for a song to have a `+` in WACCA? If there's a consistent set of requirements, I can turn this into an automated test to prevent this happening again.

**Comment by rithik-b** [comment]
I'm not sure why it was wrong
A chart is considered + if it is 0.7 or higher in its rate, if you can automate that it would be nice

**Comment by zkrising** [comment]
OK: I've added automation to the tests here and I need to pick your brain about this:

```
[ERR] charts-wacca.json | Levels <0.7 is not plus. | HIMEHINA - ヒトガタ (1) - Single HARD (336c1118cf87342549a84f5f6ecabbfdbcb80bb2) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | cosMo＠暴走P feat.初音ミク - ∞(2018Remake) (14) - Single HARD (ccbbfeb38695a9f703f65d572b8e4e5ee3a66642) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ダイナミック自演ズ - ちがう!!! (15) - Single HARD (02ea10d1347316d115063af94bbf6294f1c3398b) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ひとしずく×やま△ - 怪盗Fの台本（シナリオ）〜消えたダイヤの謎〜 (16) - Single EXPERT (967b608d762a06a25bdb4747b13a6ca33a61cdf3) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | かいりきベア - ダーリンダンス (29) - Single HARD (c51edfaa4cfa56d41218139e6854ce49a954f461) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | REDALiCE feat. 野宮あゆみ - Crime Wave (31) - Single EXPERT (efc140bc72affe42916a09062a5e12063c4de278) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | nitro (lowiro) - Let you DIVE! (nitro rmx) (37) - Single HARD (38984806113697e799eb283f5d831a5591e2e739) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Noizenecio - Machinery of Avoid (38) - Single EXPERT (c4e80c8e0dbf9827312a0f4a5aa23d32a7f63e53) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | モリモリあつし - YOG (42) - Single HARD (4f10c14f481cc5e1ce715a1c9761163dfe0a8554) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Massive New Krew - 超MANJIラッシュ (44) - Single EXPERT (186d95ce518f3dfab24ab6966923418146d9e0eb) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Massive New Krew - 超MANJIラッシュ (44) - Single HARD (7a91c444de77bee285e29bbedeec51e00c6694e3) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Yooh - Lost Illusion (49) - Single EXPERT (cc16f18549afe6c118ddf29a1de6e1fc96f2fdb5) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Yooh - Lost Illusion (49) - Single HARD (c7118176d97f82645decb299ef81733204af1388) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Polaris「アズールレーン」より - cœur (53) - Single EXPERT (cbd6ef64609766d5990fd790252a004113f542e3) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Polaris「アズールレーン」より - cœur (53) - Single HARD (5357140af29cfa8f028cf73cae9c792ce58756fd) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | HiTECH NINJA - Cauliflower (56) - Single HARD (c8560581d8b0da89941a647c64a5800ce3f665ab) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Happy Around!＆Peaky P-key 「D4DJ Groovy Mix」より - LOVE!HUG!GROOVY!! (62) - Single HARD (d030bb943e1c489c5d9ccef8adba523f0a78d3ac) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | koutaq - 四次元跳躍機関 (69) - Single EXPERT (2ad5b3fedd719c65888ec4b9821dc3402bafb96b) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 削除 feat Nikki Simmons - Destr0yer (75) - Single HARD (223c6c026d85a89716813353bb3de51fbe7364a1) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | LeaF - もぺもぺ (76) - Single EXPERT (38208205357811c67837988508149c0f53d8dc6a) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | モリモリあつし - PUPA (77) - Single EXPERT (2abcf2da86f3d968dbe07695ab7ebf6b79cb0841) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 宝鐘マリン with ホロイズムファンタジー - ホイホイ☆幻想ホロイズム (90) - Single EXPERT (4a27d5674af0e9c83ffd604f9c98828240aebe32) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | sasakure.UK - LIN NE KRO NE feat. lasah (101) - Single EXPERT (d7c59ffa298f300e444b69a0e4e7c475af48e3fe) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | REDALiCE - SHAKE! (102) - Single EXPERT (26c0f75ee94f8f6e302419d5afef795672a794d7) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Zekk - フリーフォール (104) - Single EXPERT (0292f9ee2912e12834a3d11fbcf7a40591b28da6) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | かねこちはる - 猫娘 (105) - Single EXPERT (6990e1c429530055e3ca1447547b4a1da3812635) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | YUC'e - Future Cαndy (109) - Single EXPERT (94e4007ab84714b65f36ba2f713e25d0699114ef) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | KOTONOHOUSE - PRESS START! (111) - Single EXPERT (7aaea1acc29a5616685aa8f4b8e6a5f168a07e1c) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | KOTONOHOUSE - PRESS START! (111) - Single HARD (3ef074c3628b50b4e8133ff7845d9d7f27953f3e) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Pa's Lam System - TWISTSTEP (112) - Single EXPERT (2de82ab9ca3b4937512d965d3e634b778f0f7512) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | aran & Kobaryo - はげしこの夜 -Psylent Crazy Night- (117) - Single EXPERT (7bc2410603e2752abb995f34590d1b2eb3b77e9f) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | P*Light - 恋メタル (118) - Single EXPERT (d6e5386ce275cd0dfae9c09225a1704d84f4054f) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | group_inou - THERAPY (119) - Single EXPERT (65446e3c05338ec3ecceabdc72c3709947c35841) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ミュージカル『テニスの王子様』3rdシーズン - シャカリキ・ファイト・ブンブン (120) - Single EXPERT (da35fa7218925d24dfe794cdcbfafd50f2be87af) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | t+pazolite 「グルーヴコースター」より - Good Night, Bad Luck. (124) - Single EXPERT (cb2794abd7cf45a945eadad2fcaf21ab920a70c2) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | t+pazolite 「グルーヴコースター」より - Good Night, Bad Luck. (124) - Single HARD (b8001fef8c27bd2e7003be799c16403a202f0c9b) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | aran & lapix - KALACAKLA (127) - Single EXPERT (30b6579c94e67c4eaf3baeccff80f7a9284d196f) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 源屋 - Stasis feat.motoko -WACCA EDiT- (129) - Single EXPERT (28dd34e7a39b0c25690c8149e3546d322ca25a31) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 紗倉ひびき(CV：ファイルーズあい)＆街雄鳴造(CV：石川界人) - お願いマッスル (134) - Single EXPERT (73d67ef84bb91e0f289285b6d84daf7af9f2f9c7) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 街雄鳴造（ＣＶ：石川界人） - マッチョアネーム？ (135) - Single EXPERT (c603efd8a2477549ca25b84df2df5951e040b6e6) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 井口裕香 - HELLO to DREAM (136) - Single EXPERT (da32dafff1bc300e59138f498029aa7e12ac6fcb) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | アイズ・ヴァレンシュタイン（cv.大西沙織） - トロピカッ☆バケーション (138) - Single EXPERT (b7da55db33abb29f6f20acbe8849200572ce3acb) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | REDALiCE & aran - Sweet Requiem (139) - Single EXPERT (41cceb34829753276736ab5b293ea1a8a3eedf1f) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 鈴木このみ - This game (154) - Single EXPERT (745521849887f203bc488db35186426f486e29a1) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 岸田教団&THE明星ロケッツ - 明星ロケット (165) - Single EXPERT (8d2ea21fd3b5b31d7791e5cec8a9e0d4002c9902) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | LeaF - Calamity Fortune (167) - Single EXPERT (3f4b87f59fb75ba7477fb148e6e85cae96ff18a5) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Laur - Metamorphose (183) - Single EXPERT (99b92f5ccc110242495e86f3f7990dc9237f5018) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | cosMo@暴走P - リアル初音ミクの消失 (188) - Single EXPERT (3db19ad712cff9c6520c5d22f388438e5d92a395) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ピノキオピー - おばけのウケねらい (190) - Single EXPERT (28dc978093f7432c1dc7f57018f194e85afa2e79) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ミュージカル『テニスの王子様』3rdシーズン - ガンガン・ドンドン (196) - Single EXPERT (4cd7a5d1c72060bd2b0da22baf7e9acdc14df318) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | NOMA - Brain Power (197) - Single HARD (4dd596abd2fb0de29d61590873a161185ce7c75b) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 岸田教団&THE明星ロケッツ - ストライク・ザ・ブラッド (208) - Single EXPERT (acff536ed2f5e3c8237b105b244807fce906eba9) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 岸田教団&THE明星ロケッツ - ストライク・ザ・ブラッド (208) - Single HARD (548080cc2e28d12551a2eec6de8474615aaf39bf) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Silver Forest - ケロ⑨Destiny (213) - Single EXPERT (1921164f3c6946f78674e6ca3efd5edcee2fab7d) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | E.G.G. a.k.a. COSIO - EU over Progress (225) - Single EXPERT (cef0e3b74795d547777869fe261cd7b3f81ed9f8) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | E.G.G. a.k.a. COSIO - EU over Progress (225) - Single HARD (2791ffb8fcf709bd14d1fc00e00b1b15ba0d28a5) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | aran - Mazy Metroplex (227) - Single EXPERT (ec87f547ab1edd87dfa7958cd37421939c406d6e) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | 西村 隆文 - jacaranda (243) - Single EXPERT (4a4e69f5318d73218da675c9d6e27328f6a50cb6) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Srav3R - Akareram (277) - Single EXPERT (a61d93783d325f88fdc3b1f1d24cd62b50c38d50) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ナユタン星人 - 太陽系デスコ (279) - Single EXPERT (34823ace6b33e76151a7fdd7049bc35cb07ea6b8) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Kobaryo - Galaxy Friends (280) - Single EXPERT (227a6ce6dbe94ef4792a566e9eb719bc5209cb21) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Getty - Blaze (286) - Single EXPERT (6584c86e76aae3444c720a6bc048a37f9ff80919) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Getty - Blaze (286) - Single HARD (e54ad2521dd59ce623a3b9fcdd29d335de63f33b) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | TANO*C Sound Team - BATTLE NO.1 (293) - Single EXPERT (5152e875865ddce840a669e93a5bd135a6c7a257) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Noriken - Jingle (295) - Single HARD (193a2e27b9625d98135063599e05397e6f84fe58) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Yunomi - ゲームオーバー (feat. TORIENA) (300) - Single EXPERT (fa3402c43af5aa356fa2eb93d071315d2be7c94e) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Myosuke - HELL FLAME (313) - Single EXPERT (034364f13b2fba6bcd2772aa62043e103cb3b4e1) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | GYARI(ココアシガレットP) - Seyana. ～何でも言うことを聞いてくれるアカネチャン～ (319) - Single EXPERT (35afc8eec0dd9344513418897d6122bbd8c0a18e) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | どうぶつビスケッツ×PPP - ようこそジャパリパークへ (324) - Single EXPERT (ced29dec076c16ee215c8ea83bb35b039890844d) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | フランシュシュ - 徒花ネクロマンシー (326) - Single EXPERT (f5ada2944edfecffd222f890939066cab4748d7e) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | HARDCORE TANO*C & エリザベス（CV:大西沙織） - Let you DIVE! (327) - Single HARD (5ae8ab37ea21844a22238775e06babafea3ff434) | Got 9.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ハチ - 砂の惑星 feat. 初音ミク (329) - Single HARD (3d96ecd503ce464ae9a94dc38341febb11840d7e) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Myosuke - Fight for the CORE feat. Daisuke (331) - Single HARD (3f514dc5c2216a1994b4af98c71d36d8f15d1f1f) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Genki feat. Yukacco - Rainbow Dream (341) - Single HARD (116a0f44d5c00047a0280d1709b65a8dd0120ab1) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | ゆうゆ - 天樂 (344) - Single EXPERT (6e9563006e087c39da9148a43733181403e7a59e) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | supercell - メルト (345) - Single HARD (b693625992ae937272984d96ada6966fd55419c0) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | REDALiCE - クリムゾン帝王 (347) - Single EXPERT (6df01a0b4b12dfd490b6773de9f127bad0b70a8f) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | REDALiCE - クリムゾン帝王 (347) - Single HARD (1a3d9c2ef04d645e65411d2482e0790eed94fd18) | Got 11.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | aran - EPHMR (348) - Single HARD (356ca41312750ffd7d5572505b339de0119457e4) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | t+pazolite - CENSORED!! (353) - Single HARD (45b63520d74aa78ec4a5435a324230bfb2cb3a3f) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Myosuke vs MASAKI - 神 (354) - Single EXPERT (5443c455fc0088c2f274cd718016bf0aa3fab697) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Kobaryo - GENOCIDER (Kobaryo's FTN-Remix) (358) - Single HARD (7df212ecb160596c7d3209946bc7bf8b67e3cc6d) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | USAO - You & DIE (361) - Single HARD (6f4cc4b5041e7a85b49f32fa28c2d19214808931) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Getty - GAKKY (370) - Single EXPERT (3ff4a14ee6ffa01a2b62de225623bef5765306e8) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Getty - GAKKY (370) - Single HARD (3782ebcbcc788e59806a676137e1bdc64c910b2f) | Got 10.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Noriken - NIGHTWAVE FRAGMENTS (371) - Single EXPERT (60d753dc31044b7bec8661f5d2e3f8bb6387ab3e) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Srav3R - N3XTAGE (372) - Single EXPERT (7fda1a54ae03ae9705e38842d9a85322652ea177) | Got 12.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | USAO - Big Daddy (373) - Single HARD (fddbeff70f793709ae9b1b1788b75b38d2bc7903) | Got 8.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | DJ Myosuke - 1BPM (383) - Single EXPERT (543354b25ed9e1b53ed76ea475191cf7de2da632) | Got 13.7
[ERR] charts-wacca.json | Levels <0.7 is not plus. | Gram - Odin (385) - Single HARD (7566c4881666e442370f42ae99200bd7378ef6ea) | Got 10.7
```

There are quite a lot of cases on the `x.7` border that are not marked as `x+`. Is this a bug? Or did you mean `> 0.7`, not `>= 0.7`.

**Comment by rithik-b** [comment]
I did mean 0.7 and higher, so all those should be rated + from taking a glance
I didn't recognize some of them but if they're actually not rated + they may just have incorrect rate values to begin with

**Comment by rithik-b** [comment]
I could probably try fetching all the charts from myt later today and comparing rate values to this json

**Comment by rithik-b** [comment]
Ran a script to compare levelNum from what myt has and found 2

Mismatched difficulty for 3022 EXPERT, expected 12.7 got 12.8
Mismatched difficulty for 1127 EXPERT, expected 12.1 got 12

gonna fix those now.
Other than that yes, any chart with a levelNum of .7 and higher are supposed to be + so will fix those too

**Comment by rithik-b** [comment]
Whoops I reformatted the json 🥶 lemme fix it so the diffs show better

**Comment by rithik-b** [comment]
And ready for review

**Comment by rithik-b** [comment]
NEVERMIND I JUST NOTICED A JAVASCRIPT MOMENT 
image
Taking this back to draft while i fix

**Comment by rithik-b** [comment]
So the test was incorrect which i fixed by https://github.com/zkrising/Tachi/blob/a8a167aef4b0bb9d375ebdec0a95007f3807887d/seeds/scripts/test/custom.test.ts#L74-L75

and as for the failures before, think I misinterpreted it. The test failures said that those levels shouldn't be + and they all are +. I meant they should all be + so they were correct all along.

**Comment by zkrising** [comment]
Excellent catch with the modulo thing. I thought it seemed too good to be true that my javascript was working.

**Pull request merged**
